[
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Domingos Martins",
    "ponto": "Parque Estadual Pedra Azul",
    "nome_no_mapa": "Parque Estadual Pedra Azul",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/86qCZpofHDMXyGdn9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3945515,
    "longitude": -41.0270272,
    "place_id": "ChIJmUNmcuOZuQAR9L5KEF1zpEw"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Conceição Castelo",
    "ponto": "Rota do Vale do Emboque",
    "nome_no_mapa": "Vale do Emboque",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/icZXynWSZJv8o9QbA",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3979544,
    "longitude": -41.3037475,
    "place_id": "GhIJn0ztVuBlNMAR8l61MuGmRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Laranja da Terra",
    "ponto": "Pedra dos Cinco Pontões",
    "nome_no_mapa": "Pedra dos Cinco Pontões",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/8VFzjrBNsjE4Fv2H7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.9009345,
    "longitude": -41.0560307,
    "place_id": "ChIJrWsbnL5YtwARlxr_zs1X_7M"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Marechal Floriano",
    "ponto": "Orquídeas para colecionadores (achei no google como Rota Turística Cidade das Orquideas)",
    "nome_no_mapa": "Cidade das Orquídeas",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/vM3dMRYVWYbGyBcYA",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.4112709,
    "longitude": -40.6760902,
    "place_id": "ChIJYSGo8X-0uQARb2jjr9qCFuc"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Santa maria jetibá",
    "ponto": "Museu Pomerano",
    "nome_no_mapa": "",
    "segmento": "Histórico Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/SRFt5nhDdN4u6t1Q6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.0255485,
    "longitude": -40.7443596,
    "place_id": "ChIJPQXwZ0bWuQAR6mP3wXLAdDg"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Ibatiba",
    "ponto": "Monumento aos Tropeiros",
    "nome_no_mapa": "Tropeirismo",
    "segmento": "Histórico Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/FzS9J2vprBr2oVWQ6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.235621,
    "longitude": -41.5121949,
    "place_id": "ChIJKTTgxRk6ugAR-ddf4eel5zg"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Alegre",
    "ponto": "Parque Estadual da Cachoeira da Fumaça",
    "nome_no_mapa": "",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/3WFydb83HJscb9EEA",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.6306957,
    "longitude": -41.6043233,
    "place_id": "GhIJUzr9RXWhNMAR-9pEd1rNRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Dores do Rio Preto",
    "ponto": "Portaria do Parque Nacional do Caparaó - Pico da Bandeira",
    "nome_no_mapa": "",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/gV1vrgiBhCFD2Lfv7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.4195597,
    "longitude": -41.8433836,
    "place_id": "GhIJNji2Q2hrNMARyv1p_vPrRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Divino São Lourenço",
    "ponto": "Patrimônio da Penha",
    "nome_no_mapa": "",
    "segmento": "Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/8uQ9hDRef7UUiVZ28",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.5843673,
    "longitude": -41.7607584,
    "place_id": "ChIJ_zx7M7W8uwARHLijlPhZrXQ"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "São José do Calçado",
    "ponto": "Pedra do pontão - voo livre",
    "nome_no_mapa": "",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/ecQPmdzMmRyDMeiA9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.9500884,
    "longitude": -41.5768423,
    "place_id": "GhIJGE9O_jjzNMARhrnu99XJRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Bom Jesus do Norte",
    "ponto": "Folia de Reis (não tem google meu negócio)",
    "nome_no_mapa": "",
    "segmento": "Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://www.bomjesus.es.gov.br/site/noticia/dia_de_reis_tradicao_cultural_em_bom_jesus_do_norte/881",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -21.1276729,
    "longitude": -41.6742862,
    "place_id": "ChIJNf47qEVzvAARo9BjZzSW0lI"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Aracruz",
    "ponto": "ALDEIA TEMÁTICA INDIGENA (Tekoá Mirim)",
    "nome_no_mapa": "",
    "segmento": "Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/EgqtxLMXwGmoNioG9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.9498028,
    "longitude": -40.1667426,
    "place_id": "GhIJNKa7RibzM8ARzexO0lcVRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Aracruz",
    "ponto": "PRAIAS (COQUEIRAL, FORMOSA, DOS PADRES, SANTA CRUZ, BARRA DO SAHY, PUTIRI)",
    "nome_no_mapa": "",
    "segmento": "Sol e Praia",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/Gzxbmb9cv5J8eq2H9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.9034757,
    "longitude": -40.0986926,
    "place_id": "ChIJHSirLwLntwARMbD2NOvYa4w"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Fundão",
    "ponto": "PICO DO GOIAPABA AÇU",
    "nome_no_mapa": "",
    "segmento": "Ecoturismo e Aventura",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/rs1avRagLJnaBXZa7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.9147876,
    "longitude": -40.4753761,
    "place_id": "GhIJTckohS_qM8ARZ2bBH9k8RMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Ibiraçu",
    "ponto": "CAMINHOS DA SABEDORIA \nGRANDE BUDA (ESTAÇÃO FERROVIÁRIA,PRAÇA TORI, ROTEIRO DA ILUMINAÇÃO, ESCOLA DE CERAMICA, MONSTEIRO ZEN BUDISTA)\nSANTUÁRIO NOSSA SENHORA DA SAUDE",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/h5xRWhKGikHv7ifM8   (google meu negócio do caminhos da sabedoria, pode-se escolher algum desses pontos)",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.82929,
    "longitude": -40.3566995,
    "place_id": "GhIJXOZ0WUzUM8AR8X9HVKgtRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "João Neiva",
    "ponto": "DISTRITO DEMÉTRIO RIBEIRO (MUSEU DO IMIGRANTE, CASA DE PEDRA, CASARÃO DOS VIOLINOS, FESTA ITAIA MIA)",
    "nome_no_mapa": "",
    "segmento": "Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/3pHSdJMNgnm3xj9u6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.756871,
    "longitude": -40.3771664,
    "place_id": "ChIJC1oXZWS-twAR_iAYyOL_DaY"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Santa Teresa",
    "ponto": "CIRCUITO CARAVAGGIO ",
    "nome_no_mapa": "",
    "segmento": "Gastronomia",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/DJBHHGduTkgD7C2f7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.9227823,
    "longitude": -40.6401153,
    "place_id": "ChIJpT6CPIR4twARNjnvkpayC5c"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Santa Teresa",
    "ponto": "MUSEU DA CULTURA E IMIGRAÇÃO ITALIANA",
    "nome_no_mapa": "",
    "segmento": "Histórico Cultural",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/pFJgv7TgXYhC5vJ79",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.9300197,
    "longitude": -40.5990021,
    "place_id": "ChIJe4koOECDtwARPdT_sd29kfs"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Linhares",
    "ponto": "Lagoa Juparanã - praia das 03 pontas",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/nwfyPBACMaUdYuZF6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.2717741,
    "longitude": -40.1401539,
    "place_id": "ChIJW6u232QjtgARr8-2Cd6TejU"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Linhares",
    "ponto": "Praia de Regência",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/hNoNM2xSdMQRtFRM7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.6716518,
    "longitude": -39.8829842,
    "place_id": "GhIJr0xTX_GrM8ARPvFSoAXxQ8A"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Sooretama",
    "ponto": "Reserva de Sooretama -",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/MPdSLrdjHYjRTTL1A",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.0076631,
    "longitude": -40.1165673,
    "place_id": "GhIJz-J7NfYBM8AROqRiresORMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Vila Valério",
    "ponto": "Cachoeira da Barra Seca",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/S8wurVkXLnm1HDyf8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.0898714,
    "longitude": -39.7226188,
    "place_id": "ChIJcYh8PxD0yQARqtLrqgVx4C0"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Rio Bananal",
    "ponto": "Ilha do Imperador",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/TXdwvw4MczLSQe3a7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.2717741,
    "longitude": -40.1401539,
    "place_id": "ChIJW6u232QjtgARr8-2Cd6TejU"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Alto Rio Novo",
    "ponto": "Pico dos Abelheiros",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/f1y1VqctvVt8fYhB7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.0260806,
    "longitude": -41.0708354,
    "place_id": "GhIJYA_cN60GM8ARFTNnIhGJRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Baixo Guandu",
    "ponto": "Rampa do Monjolo (voo livre) /",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/suAQr8cmXkV6fNR66",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.6313367,
    "longitude": -40.9681156,
    "place_id": "ChIJd7A0yQdAtwAREjAq2Y9YrSg"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Itarana",
    "ponto": "Tombo da Papa (endereço de onde acontece a festa/ não achei site fixo ou google mue negócio)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/ygR2JXpUTQJnRSMx6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.872623,
    "longitude": -40.8752658,
    "place_id": "ChIJucW1ix5ktwARm3tHKx-ko7o"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Pancas",
    "ponto": "Monumento Natural Pontãos Capixabas",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/mcqyGzb1EPjFZTYq9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.2228757,
    "longitude": -40.8528533,
    "place_id": "ChIJjba78LnltgARjkzLW9u1bO0"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Colatina",
    "ponto": "Rota / Mirante São Pedro Frio",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/gSFVfSQ5v5v1rLQe9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -19.373421,
    "longitude": -40.8071932,
    "place_id": "GhIJvqPGhJhfM8AR3MZVG1JnRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "vitoria",
    "ponto": "CENTRO HISTÓRICO Cultura e arte - Teatro Carlos Gomes, Teatro Glória, Museu do Negro, Palácio do Governo, Catedral, Galeria Homero Massena, Museu de Arte, FAFI, Gruta da Onça",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/g4QRYkqwBqq2iFmMA",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -22.9204249,
    "longitude": -43.1744643,
    "place_id": "ChIJF0pBIdaBmQAR2tkOYyP--M0"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "vitoria",
    "ponto": "Paneleiras de Goiabeiras",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/3dPtBVX53QPLJe8K7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.2694404,
    "longitude": -40.3033253,
    "place_id": "ChIJn-DSscwZuAARjYaB1hhZQr8"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "serra",
    "ponto": "MANGUINHOS- SOL E PRAIA",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/3cAmNu4n1hdTsgmr7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.1933341,
    "longitude": -40.198398,
    "place_id": "ChIJX174SU0cuAARTz10G-KYHz4"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "serra",
    "ponto": "SERRA SEDE- HISTÓRICO/RELIGIOSO ( IGREJA MATRIZ/ CHICO PREGO/ QUEIMADOS/ CONGO- FESTA SÃO BENEDITO, associação das bandas de congo ABC)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/qrydKhXCGW83yCr27",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.1279874,
    "longitude": -40.3081052,
    "place_id": "EjtBdi4gR2V0w7psaW8gVmFyZ2FzLCAxNDggLSBTZXJyYSBDZW50cm8sIFNlcnJhIC0gRVMsIEJyYXppbCIbEhkKFAoSCb9zfrD4H7gAEeDgMN99WRXuEJQB"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "cariacica",
    "ponto": "Sítio Histório (Trio Histórico) em Cariacica Sede - Igreja, Praça e Prédio da Prefeitura",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/U3RPPLzsttM5ZeCy6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.2667124,
    "longitude": -40.4183037,
    "place_id": "ChIJg5MmDD07uAARagKBDo8lI84"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "cariacica",
    "ponto": "Pier - Orla de Cariacica",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/oGQ4pajuA4SAL7PY7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3137143,
    "longitude": -40.3680308,
    "place_id": "ChIJC1Bp-kI8uAARP3OR86xPo-8"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "viana",
    "ponto": "Estação ferroviária",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/9dXoUZwWESB7W5Nw8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.389933,
    "longitude": -40.4914084,
    "place_id": "ChIJH91BSR9IuAARBm9tw9_uTM0"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "viana",
    "ponto": "Igrejas centenárias (nossa senhora da conceição)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/zX4EC5x23cTCGh2U8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3668666,
    "longitude": -40.421581,
    "place_id": "ChIJ24KCRww5uAARtfgqtFA3Ayk"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "vila velha",
    "ponto": "CONVENTO DA PENHA",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/iSVeVHZTuCTrHEfb9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3293623,
    "longitude": -40.287069,
    "place_id": "GhIJDAlzFlFUNMARA1lPrb4kRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "vila velha",
    "ponto": "MORRO DO MORENO",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/1EiKChJ4bAETb5wu5",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3263068,
    "longitude": -40.2774635,
    "place_id": "ChIJixdqrlIWuAARlfIafNUX-qk"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "vila velha",
    "ponto": "FAROL DE SANTA LUZIA - PRAIA SECRETA",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/VV7FmnLpF9pQgPXr9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.3246492,
    "longitude": -40.2680519,
    "place_id": "ChIJkUhKVQcXuAARHobQyhlIlNc"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "ÁGUIA BRANCA",
    "ponto": "Cultura - Casa do Polonês\nCaminhada do Imigrante Polonês",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/FXhu7bzsk7JTEab46",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.9864622,
    "longitude": -40.7375836,
    "place_id": "ChIJL-AD8r6PtgARP9decjFFNig"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "BOA ESPERANÇA",
    "ponto": "Pedra da Botelha - ciclismo - barragem - aventura",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/TFRxSaheYsp1GNxp7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.4461248,
    "longitude": -40.3705008,
    "place_id": "GhIJPu8hPDVyMsARJ5L5kWwvRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "NOVA VENÉCIA",
    "ponto": "Pedra do Elefante - APA/Aventura/Rural/ecoturismo/religioso\nSantuário Mae Peregrina\nRecanto das Pedras\nPedra do Tubarão\nFazenda Santa Rita\nSitio Pedra do Elefantinho\nCasarão dos escravos",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/E2vKUqsn3BNeEofUA",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.7084516,
    "longitude": -40.3955098,
    "place_id": "ChIJ_7knp17btQARQFEspv6hOiw"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "sao mateus",
    "ponto": "Sitio Histórico",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/muA2oPNH6PUxL1zR8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.716613,
    "longitude": -39.8558783,
    "place_id": "ChIJe4ooA6sNygARWq5fDchG2QE"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "CONCEIÇÃO DA BARRA",
    "ponto": "Distrito de Itaúnas (Praia, Riacho Doce, dunas, parque, FANFIT, Reveillon)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/kAzWnJYsK6yEZuWN9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.413573,
    "longitude": -39.6974212,
    "place_id": "GhIJNIKN699pMsARv8QOGUXZQ8A"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "PEDRO CANÁRIO",
    "ponto": "Lagoa Augusto Ruschi",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/JkzQBENc3ehuApBu7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.2979712,
    "longitude": -39.9547765,
    "place_id": "ChIJCYvEtUyAygARdcdo1XFtfMI"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "MONTANHA",
    "ponto": "Festival Gastronomico da Carne de Sol (não tem google meu negocio, coloquei o insta e a localização de onde acontece)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://www.instagram.com/festivaldemontanhaes/",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.1262369,
    "longitude": -40.3596626,
    "place_id": "ChIJ7VkILFAMtQARR0pR_iF5CEc"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "MUCURICI",
    "ponto": "Balneário de Mucurici",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/LfjUhADEEYYoyJSo7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -18.093338,
    "longitude": -40.519165,
    "place_id": "ChIJHwSUNUkEtQAR7DAmFmB8J-Y"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Presidente Kennedy",
    "ponto": "Praias: Neves - Igreja, Marobá, - Pantanal / pesca - Evento: Bike Fest\nMarisqueiras - gastronomia",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/W3tiQru57WnzjBiLA",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -21.192478,
    "longitude": -40.9282326,
    "place_id": "ChIJmdeH2zE1uQARhgr6lN0LVWM"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Atílio Vivácqua",
    "ponto": "Pedra do Caramba, Caveira e do Indio ( mirante / vista do vale)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/pmrU93Zjij41WPxe6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.9147218,
    "longitude": -41.135749,
    "place_id": "GhIJMfA3NSvqNMARe7slOWCRRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Vargem Alta",
    "ponto": "Frade e Freira (em construção), Pedreiras e Itabira: escalada / caminhada / observação de aves",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/oC3VNC7k9NFWANS67",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.8686656,
    "longitude": -40.9937807,
    "place_id": "GhIJBCln3mDeNMARr_K6NDR_RMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Muqui",
    "ponto": "Sitio Histórico - casarios -",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/kbYctKymxDGKc74n8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.9510499,
    "longitude": -41.3453279,
    "place_id": "ChIJM7v6jXn9uwARM0VlbHa9gFk"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Mimoso do Sul",
    "ponto": "Monumento Natural S das Torres - Monaste // Pico dos Pontões - RPPN",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/rCSakEzxDmto2c62A",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.9402363,
    "longitude": -41.5549992,
    "place_id": "GhIJFQN_U7PwNMARMKe6NgrHRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Marataízes",
    "ponto": "Praias e Praças/Praia/ Falésias",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/PUg9nqKbGRYzYncD9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -21.1442635,
    "longitude": -40.8831559,
    "place_id": "GhIJqYHmc-4kNcARfuKlQAtxRMA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Rio Novo do Sul",
    "ponto": "Festa da Juçara (não tem google meu negócio, coloquei o local aonde acontece)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/AKgLcjKoWzwxq59X9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.8634051,
    "longitude": -40.9317438,
    "place_id": "ChIJAVPtphMVuQARXRugalyh06I"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Castelo",
    "ponto": "Festa religiosa/CorpusChrist/tapetes (não tinha google meu negócio, coloquei a igreja que faz os tapetes)\nSantuário Aracui",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/PbjA3LuUGMfxjpts7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.640742,
    "longitude": -41.2096279,
    "place_id": "ChIJM9QZ6K98uQARbvq3W9AElFc"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Cachoeiro",
    "ponto": "Roberto Carlos: Casa e Praça",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/HG7KbAgqaeQga7rs8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.8517991,
    "longitude": -41.1148627,
    "place_id": "ChIJXV9gAcpCuQAR3MvWddFuEHA"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Cachoeiro",
    "ponto": "Fábrica dos Pios",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/XfD1pDCz2zMMJZA3A",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.838043,
    "longitude": -41.121561,
    "place_id": "ChIJ5T9h4VJduQAR3KXokIa0H5I"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Itapemirim",
    "ponto": "Monte Agá",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/e8MBykUvNYrLZNcT7",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.849802,
    "longitude": -40.75189,
    "place_id": "ChIJ2113BdIbuQAR6alSIotbIA4"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Anchieta",
    "ponto": "Santuário São José de Anchieta",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/ewWQuNQK43u6WJQD9",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.8041901,
    "longitude": -40.6537579,
    "place_id": "ChIJ47_537UCuQARvv7Cr9_arRc"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Alfredo Chaves",
    "ponto": "Matilde: Cachoeira Alta (Cachoeiro do Engenheiro Reeve)",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/1kLeDsmvtAcq6tpY8",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.5590039,
    "longitude": -40.8165275,
    "place_id": "ChIJvaOINkCnuQARDjluujw0Qa4"
  },
  {
    "ancora": "SIM",
    "cep": "",
    "rua": "",
    "bairro": "",
    "cidade": "Guarapari",
    "ponto": "Praia do Ulé | Setiba |Morro| Areia Preta| Castanheiras | Bacutia| Peracanga |Meaípe | Praia dos Padres | Setiba | 3 praias",
    "nome_no_mapa": "",
    "segmento": "",
    "categoria": "",
    "atrativo": "",
    "google_meu_negocio": "https://maps.app.goo.gl/3hwJJnYUaYjQ3kNS6",
    "estado": "ES",
    "pais": "Brasil",
    "latitude": -20.7330894,
    "longitude": -40.5299612,
    "place_id": "ChIJy16uQSD5uAARLRAuJNRkuSw"
  }
]